name: Primer WorkFlow

on: push

jobs: 
  validar: 
    runs-on: ubuntu-latest

    steps: 
      - name: Descargar el codigo
        run: git clone https://github.com/ulopeznovoa/AS-CI-CD-ej1/blob/main/test.py
      
      - name: Instalar pytest
        run: pip install pytest

      - name: Utilizar pytest
        run: pytest test.py
        
