name: Primer WorkFlow

on: push

jobs: 
  validar: 
    runs-on: ubuntu-latest

    steps: 
      - name: Descargar el codigo
        uses: actions/checkout@v5

      - name: Crear imagen Docker
        run: docker build -t ulopeznovoa/holamundo .

      - name: Probar docker
        run: docker run ulopeznovoa/holamundo
        
