name: Primer WorkFlow

on: push

jobs: 
  validar: 
    runs-on: ubuntu-latest

    steps: 
      - name: Descargar el codigo
        uses: actions/checkout@v5
      
      - name: Instalar pytest
        run: pip install pytest

      - name: Utilizar pytest
        run: pytest test.py
        
